parameters:
  - name: customParameter1
    type: string
    default: ''
  - name: customParameter2
    type: string
    default: ''
  - name: customParameter3
    type: string
    default: ''

jobs: 
- job: HostedAgent
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: TerraformInstaller@0
    inputs: 
      terraformVersion: latest
    displayName: Install Terraform
  - script: |
      echo "Custom Parameter 1: $(customParameter1)"
      echo "Custom Parameter 2: $(customParameter2)"
      echo "Custom Parameter 3: $(customParameter3)"
    displayName: 'Output Parameters'
  - template: windows/createvm.yml  # Template reference
