parameters:
- name: customParameter1
  type: string
  default: ' '

- name: customParameter2
  type: string
  default: ' '

- name: customParameter3
  type: string
  default: ' '

jobs: 
- job: HostedAgent
  pool:
    vmImage: 'windows-latest'
  steps:
  - powershell: |
      Write-Host "##vso[task.setvariable variable=myVar;]foo"
  - powershell: |
      Write-Host "You can use macro syntax for variables: $(myVar)"
  - task: TerraformInstaller@0
    inputs: 
      terraformVersion: latest
    displayName: Install Terraform
  - script: |
      echo "Setting Custom Parameter 2 Value..."
      echo "##vso[task.setvariable variable=CUSTOM_PARAM_2;isOutput=true]$(customParameter2)"

  - script: |
      echo "Setting Custom Parameter 3 Value..."
      echo "##vso[task.setvariable variable=CUSTOM_PARAM_3;isOutput=true]$(customParameter3)"

  - script: |
      echo "Custom Parameter 1 Value: $(CUSTOM_PARAM_1)"
      echo "Custom Parameter 2 Value: $(CUSTOM_PARAM_2)"
      echo "Custom Parameter 3 Value: $(CUSTOM_PARAM_3)"
    displayName: 'Print Custom Parameter'
  - template: windows/createvm.yml  # Template reference
