- job: Windows
  pool:
    vmImage: 'windows-latest'
  steps:
  - script: echo This script runs before the template's steps, only on Windows.
  - template: windows/createvm.yml  # Template reference
  - script: echo This step runs after the template's steps.