jobs: 
- job: HostedAgent
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: TerraformInstaller@0
    inputs: 
      terraformVersion: latest
    displayName: Install Terraform
  - script: |
      echo "TESTIMG: $(TESTIMG)"
      echo "ISSUE: $(ISSUE)"
      echo "TEST: $(TEST)"
    displayName: 'Output Parameters'
  - script: |
      echo "##vso[task.setvariable variable=TESTIMG]$(TESTIMG)"
      echo "##vso[task.setvariable variable=ISSUE]$(ISSUE)"
      echo "##vso[task.setvariable variable=TEST]$(TEST)"
    displayName: 'Set Variables'
  - powershell: |
      $psexecUrl = 'https://download.sysinternals.com/files/PSTools.zip'
      $downloadPath = Join-Path $env:USERPROFILE 'Downloads\PSTools.zip'
      Invoke-WebRequest -Uri $psexecUrl -OutFile $downloadPath
      Expand-Archive -Path $downloadPath -DestinationPath $env:USERPROFILE\Downloads\PSTools
      $psexecPath = Join-Path $env:USERPROFILE\Downloads\PSTools 'PsExec.exe'
      Copy-Item -Path $psexecPath -Destination 'C:\Windows\System32\PsExec.exe'
      [System.Environment]::SetEnvironmentVariable('Path', [System.Environment]::GetEnvironmentVariable('Path', [System.EnvironmentVariableTarget]::Machine) + ";$psexecPath", [System.EnvironmentVariableTarget]::Machine)
      psexec
    displayName: 'Download and Install PsExec'
