parameters:
- name: customParameter1
  type: string
  default: ' '

- name: customParameter2
  type: string
  default: ' '

- name: customParameter3
  type: string
  default: ' '

jobs: 
- job: HostedAgent
  pool:
    vmImage: 'windows-latest'
  steps:
  - powershell: |
      # 환경 변수로 값을 설정
      $env:CUSTOM_PARAM_1 = "$(customParameter1)"
      $env:CUSTOM_PARAM_2 = "$(customParameter2)"
      $env:CUSTOM_PARAM_3 = "$(customParameter3)"
  - powershell: |
      # 환경 변수 사용
      Write-Host "You can use macro syntax for variables: $env:CUSTOM_PARAM_1"
      Write-Host "You can use macro syntax for variables: $env:CUSTOM_PARAM_2"
      Write-Host "You can use macro syntax for variables: $env:CUSTOM_PARAM_3"
  - task: TerraformInstaller@0
    inputs: 
      terraformVersion: latest
    displayName: Install Terraform
  - template: windows/createvm.yml  # Template reference

