jobs: 
- job: HostedAgent
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: TerraformInstaller@0
    inputs: 
      terraformVersion: latest
    displayName: Install Terraform
  - script: |
      echo "TESTIMG: $(TESTIMG)"
      echo "ISSUE: $(ISSUE)"
      echo "TEST: $(TEST)"
    displayName: 'Output Parameters'
  - script: |
      echo "##vso[task.setvariable variable=TESTIMG]$(TESTIMG)"
      echo "##vso[task.setvariable variable=ISSUE]$(ISSUE)"
      echo "##vso[task.setvariable variable=TEST]$(TEST)"
    displayName: 'Set Variables'
  - powershell: |
# PsExec 다운로드 URL
    $psexecUrl = 'https://download.sysinternals.com/files/PSTools.zip'

# 다운로드 경로
    $downloadPath = Join-Path $env:USERPROFILE 'Downloads\PSTools.zip'

# 다운로드
    Invoke-WebRequest -Uri $psexecUrl -OutFile $downloadPath

# 압축 해제
    Expand-Archive -Path $downloadPath -DestinationPath $env:USERPROFILE\Downloads\PSTools

# psexec 실행 파일 경로
    $psexecPath = Join-Path $env:USERPROFILE\Downloads\PSTools 'PsExec.exe'

# 복사해서 C:\Windows\System32로 이동
    Copy-Item -Path $psexecPath -Destination 'C:\Windows\System32\PsExec.exe'

# 환경 변수에 추가 (옵션)
    [System.Environment]::SetEnvironmentVariable('Path', [System.Environment]::GetEnvironmentVariable('Path', [System.EnvironmentVariableTarget]::Machine) + ";C:\Windows\System32", [System.EnvironmentVariableTarget]::Machine)
# psexec 실행 여부 확인
    psexec
    displayName: 'Download and Install PsExec'