jobs: 
- job: HostedAgent
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: TerraformInstaller@0
    inputs: 
      terraformVersion: latest
    displayName: Install Terraform
  - script: |
      echo "TESTIMG: $(TESTIMG)"
      echo "ISSUE: $(ISSUE)"
      echo "TEST: $(TEST)"
    displayName: 'Output Parameters'
  - script: |
      echo "##vso[task.setvariable variable=TESTIMG]$(TESTIMG)"
      echo "##vso[task.setvariable variable=ISSUE]$(ISSUE)"
      echo "##vso[task.setvariable variable=TEST]$(TEST)"
    displayName: 'Set Variables'
  - powershell: |
      echo "TESTIMG: $env:TESTIMG"
      echo "ISSUE: $env:ISSUE"
      echo "TEST: $env:TEST"
    displayName: 'Output Variables'
  - powershell: |
      $psexecUrl = 'https://download.sysinternals.com/files/PSTools.zip'
      $downloadPath = Join-Path $env:USERPROFILE 'Downloads\PSTools.zip'
      Invoke-WebRequest -Uri $psexecUrl -OutFile $downloadPath
      Expand-Archive -Path $downloadPath -DestinationPath $env:USERPROFILE\Downloads\PSTools
      $psexecPath = Join-Path $env:USERPROFILE\Downloads\PSTools 'PsExec.exe'
      Copy-Item -Path $psexecPath -Destination 'C:\Windows\System32\PsExec.exe'
      [System.Environment]::SetEnvironmentVariable('Path', [System.Environment]::GetEnvironmentVariable('Path', [System.EnvironmentVariableTarget]::Machine) + ";$psexecPath", [System.EnvironmentVariableTarget]::Machine)
    #psexec -accepteula \\20.196.215.86 -u Tester -p Tester1234@! -i 2 -h cmd /C start /MIN C:/test2.bat $env:TESTIMG $env:ISSUE $env:TEST
    
    #psexec -accepteula \\20.196.215.86 -u Tester -p Tester1234@! -i 2 -h cmd /C "cd C:\CLOUD\test\v6 && mvn compile && exit"
    displayName: 'Download and Install PsExec'
  - powershell: |
      $escapedTestImg = $env:TESTIMG -replace '"', '\"'
      $escapedIssue = $env:ISSUE -replace '"', '\"'
      $escapedTest = $env:TEST -replace '"', '\"'
      psexec -accepteula \\20.196.215.86 -u Tester -p Tester1234@! -i 2 -h cmd /C start /MIN C:/test2.bat "$escapedTestImg" "$escapedIssue" "$escapedTest"
    # psexec -accepteula \\20.196.215.86 -u Tester -p Tester1234@! -i 2 -h cmd /C start /MIN C:/test2.bat $(TESTIMG) $(ISSUE) $(TEST)
    displayName: 'Run PsExec'
