parameters:
- name: customParameter1
  type: string
  default: ' '

- name: customParameter2
  type: string
  default: ' '

- name: customParameter3
  type: string
  default: ' '

jobs: 
- job: HostedAgent
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: TerraformInstaller@0
    inputs: 
      terraformVersion: latest
    displayName: Install Terraform
  - template: windows/createvm.yml  # Template reference
  - script: |
      echo "Custom Parameter 1 Value: $(customParameter1)"
      echo "Custom Parameter 2 Value: $(customParameter2)"
      echo "Custom Parameter 3 Value: $(customParameter3)"
      echo "##vso[task.setvariable variable=CUSTOM_PARAM_1]$(customParameter1)"
      echo "##vso[task.setvariable variable=CUSTOM_PARAM_2]$(customParameter2)"
      echo "##vso[task.setvariable variable=CUSTOM_PARAM_3]$(customParameter3)"
    displayName: 'Print Custom Parameter'