jobs: 
- job: HostedAgent
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: TerraformInstaller@0
    inputs: 
      terraformVersion: latest
    displayName: Install Terraform
  - script: |
      echo "TESTIMG: $(TESTIMG)"
      echo "ISSUE: $(ISSUE)"
      echo "TEST: $(TEST)"
    displayName: 'Output Parameters'
  - template: windows/createvm.yml  # Template reference
