parameters:
- name: customParameter1
  type: string
  default: ' '

- name: customParameter2
  type: string
  default: ' '

- name: customParameter3
  type: string
  default: ' '

jobs: 
- job: HostedAgent
  pool:
    vmImage: 'windows-latest'
  steps:
  - powershell: |
      Write-Host "##vso[task.setvariable variable=CUSTOM_PARAM_1;]$(customParameter1)"
      Write-Host "##vso[task.setvariable variable=CUSTOM_PARAM_2;]$(customParameter2)"
      Write-Host "##vso[task.setvariable variable=CUSTOM_PARAM_3;]$(customParameter3)"
  - powershell: |
      Write-Host "You can use macro syntax for variables: $(customParameter1)"
      Write-Host "You can use macro syntax for variables: $(customParameter2)"
      Write-Host "You can use macro syntax for variables: $(customParameter3)"
  - task: TerraformInstaller@0
    inputs: 
      terraformVersion: latest
    displayName: Install Terraform
  - template: windows/createvm.yml  # Template reference

