jobs: 
- job: HostedAgent
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: TerraformInstaller@0
    inputs: 
      terraformVersion: latest
    displayName: Install Terraform
  - script: |
      echo "TESTIMG: $(TESTIMG)"
      echo "ISSUE: $(ISSUE)"
      echo "TEST: $(TEST)"
    displayName: 'Output Parameters'
  - script: |
      echo "##vso[task.setvariable variable=TESTIMG]$(TESTIMG)"
      echo "##vso[task.setvariable variable=ISSUE]$(ISSUE)"
      echo "##vso[task.setvariable variable=TEST]$(TEST)"
    displayName: 'Set Variables'
  - template: windows/azure-vm-start.yml  # Template reference
